---
name: Lint Code Base

on:
  push
  # pull_request  # ← Optional, uncomment if you want this on PRs too

permissions:
  contents: read  # ✅ Fixes Checkov warning about write permissions

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v6.5.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync workflow to Port.io dashboard
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORTCLIENTID }}           # ← Using your actual secret names
          clientSecret: ${{ secrets.PORTCLIENTSECRET }}
          baseUrl: https://api.port.io
          operation: UPSERT
          identifier: lint-${{ github.run_id }}
          title: "Lint Code Base Run #${{ github.run_number }}"
          blueprint: workflow_run
          properties: '{}'
