---
name: Lint Code Base

on: push  # You can also add `pull_request` here if you want to lint PRs too

permissions:
  contents: read  # ✅ Fixes CHECKOV security warning

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required so Super-Linter can detect changes properly

      - name: Lint Code Base
        uses: super-linter/super-linter@v6.5.0  # ✅ Updated to maintained version
        env:
          VALIDATE_ALL_CODEBASE: false  # Only lint changed files
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for Super-Linter
